fix(reactmultiemail): account for emails being entered as "Name <name…
axisj/react-multi-email pull request #127
Opened 2023-07-13 15:43 UTC by jhaltercmu2020

…@domain.com>"

account for emails being entered as "Name <name@domain.com>"

2023-07-14 01:46 UTC, thomasJang requested changes
<img width="548" alt="image" src="https://github.com/axisj/react-multi-email/assets/5884902/913a5a8f-a806-4867-acef-c23f68e079bf">
If you enter the value and enter the Enter key as shown in the picture, it doesn't work.

2023-07-14 01:46 UTC, thomasJang commented on react-multi-email/ReactMultiEmail.tsx
> +      const isNameFormat = value.includes("<") && value.includes(">") ? true : false;
I think there's a simple way to make the code like below
```
const isNameFormat = value.includes('<') && value.includes('>');
```

2023-07-14 14:02 UTC, jhaltercmu2020 commented on react-multi-email/ReactMultiEmail.tsx
> +      const isNameFormat = value.includes("<") && value.includes(">") ? true : false;
@thomasJang This is much simpler. I will make this change.

2023-07-14 14:04 UTC, jhaltercmu2020 commented
> <img alt="image" width="548" src="https://user-images.githubusercontent.com/5884902/253444550-913a5a8f-a806-4867-acef-c23f68e079bf.png">
> If you enter the value and enter the Enter key as shown in the picture, it doesn't work.

@thomasJang Copy and Paste works but something is definitely broken when trying to type emails in that format. I will fix it and let you know when I have it working so you can try again. Thank you for reviewing!

2023-07-15 01:16 UTC, thomasJang commented
@jhaltercmu2020 

Thank you for your effort.
And if possible, I think it would be good to use regular expressions to check if 'value' is an email pattern.
And furthermore, I thought it would be better to provide email patterns as an option for users to choose from.

2023-07-17 18:53 UTC, jhaltercmu2020 commented
@thomasJang I made some updates based on your comments. Can you take a look? Thank you!

2023-07-18 13:39 UTC, thomasJang approved these changes
Thank you !

2023-07-21 12:40 UTC, jhaltercmu2020 commented
@thomasJang Would you be able to tag 2 other colleagues to review this?

2023-07-22 01:35 UTC, vinyl810 approved these changes
Sorry for the late review. Looks good to me.

2023-07-23 13:07 UTC, hwonda approved these changes
thank you for your contribution. Looks good to me.

2023-07-23 13:08 UTC, merged

2023-10-20 15:42 UTC, jhaltercmu2020 commented
@hwonda @thomasJang When is the next release scheduled to happen? We are wondering if this can get deployed so we can install the new dependency in our project?

2023-10-23 00:16 UTC, thomasJang commented
It 1.0.17 is just out, sorry for late, Thank you for your effort.