fix : undefined trim error
axisj/react-multi-email pull request #167
Opened 2023-11-23 09:26 UTC by hovelopin

**[ 관련 이슈 ]** 

#166 

**[문제사항]**

해당 부분을 살펴보고 테스트해보니까 ,(콤마) ;(세미콜론) 공백(space) 모두 에러가 발생했고 배열이 비어있을때 `arr[0].trim()`하는 과정에서 에러가 발생했던 것 같아 해당 부분을 제거하려고 했으나 다른 이슈와 연관(#165)되어 있어서 undefined일때 return하는 방식으로 해결하였습니다.

2023-11-23 09:30 UTC, thomasJang approved these changes
수고하셨습니다.

2023-11-23 09:56 UTC, 134130 requested changes
arr[0] 가 undefined 일 경우가 언제가 있을까 생각해보고, do-while 문의 조건을 조정하여 처리하는 것이 적절

2023-11-23 12:26 UTC, hovelopin commented
안녕하세요 지환님! 
먼저 리뷰 남겨주셔서 감사합니다. 

말씀하신 내용은 do-while문의 조건으로 남겨달라고 말씀해주신것 같은데 do-while의 경우에는 while에 있는 조건을 확인하지 않고 do에 해당하는 로직이 일단 먼저 실행하게 되는것으로 알고 있는데 해당 부분은 첫입력시 문제가 발생하는 부분이 있어서 첫 입력부터 조건을 확인해야하는 상황인것 같아요! do-while문으로 해당 부분도 처리가 가능한걸까요?

2023-11-23 14:10 UTC, 134130 commented
@hovelopin 안녕하세요!

말씀주신 것 처럼 do-while 문은 do를 먼저 실행하고 조건울 검사합니다.

현재 코드상으로 0번 인덱스가 undefined인 경우 문제가 있는데요.
말씀주신 것 처럼 최초 1회에 한해 발생한다면, do-while문 외부에서 처리하는게 적절합니다.
또한, while문으로 교체하여 문제를 해결할 수 있어보입니다.

감사합니다.

2023-11-24 00:36 UTC, thomasJang commented
사실 크게 중요한 부분은 아니라 생각해서 그냥 넘길까 했지만 
기왕이면 더 예쁘게 짜는게 개발자의 미덕이니.
아래 코드가 참조가 되시면 좋겠습니다.

근데 어쩌다 이런 코드가 들어와 있을까요 ^^

```
const value = ',';
const re = /,/;
const setArr = new Set(value.split(re).filter((n) => n));
const arr = [...setArr];
console.log(arr);

while (arr.length) {
  console.log('while', arr[0]);
}

do {
  console.log('do', arr[0]);
} while (arr.length);

```

2023-11-24 01:22 UTC, merged